# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "emoji_maker" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "emoji_maker" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: ENV_VAR_TEST
              value: {{ .Values.envVarTest }}
            # Add more environment variables as needed

